apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mychart.fullname" . }}
  labels:
    {{ include "mychart.deploymentLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mychart.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "mychart.name" . }}
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.mongodbRootUsername }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "{{ .Values.mongodbRootPassword }}"
