apiVersion: v1
kind: Service
metadata:
  name: {{ template "mychart.fullname" . }}
  labels:
    {{ include "mychart.serviceLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 27017
  selector:
    app: {{ template "mychart.name" . }}
