apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app
  namespace: elastic-stack
  labels:
    app: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
      - name: log-app
        image: nikhil666/log-app:v2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: log-app-service
  namespace: elastic-stack
  labels:
    app: log-app
spec:
  type: NodePort
  selector:
    app: log-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
